name: Build Android APK

on:
  push:
    branches:
      - main  # main branch push হলে trigger হবে

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Expo CLI
        run: npm install -g expo-cli eas-cli

      - name: Install dependencies
        run: yarn install

      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas login --token $EXPO_TOKEN

      - name: Build Android APK
        run: eas build --platform android --profile production --non-interactive

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: |
            ./dist/*.apk
